[cerebrium.deployment]
name = "mtailor-imagenet-classifier"
python_version = "3.10"
include = ["app.py","model.py","models/model.onnx","requirements.txt","cerebrium.toml","Dockerfile"]
exclude = []

[cerebrium.hardware]
cpu = 2
memory = 8.0
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.runtime.custom]
port = 8192
healthcheck_endpoint = "/health"
dockerfile_path = "./Dockerfile"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 1
replica_concurrency = 100